from dataclasses import dataclass, field
from typing import List, Optional, Any # Added Any for placeholder

# Assuming CoTConfig is in src.cot_process
try:
    from src.cot_process import CoTConfig
except ImportError:
    # Minimal placeholder if running this part in isolation before src.cot_process exists
    @dataclass
    class CoTConfig: # type: ignore
        pass

from src.aot_constants import (
    DEFAULT_MAIN_MODEL_NAMES, DEFAULT_MAX_STEPS, DEFAULT_MAX_TIME_SECONDS,
    DEFAULT_NO_PROGRESS_LIMIT, DEFAULT_MAIN_TEMPERATURE
)

@dataclass
class LLMCallStats: # This definition should remain as it's widely used
    completion_tokens: int = 0
    prompt_tokens: int = 0
    call_duration_seconds: float = 0.0
    model_name: Optional[str] = None

@dataclass
class ParsedLLMOutput: # Remains unchanged
    valid_steps_for_trace: List[str] = field(default_factory=list)
    all_lines_from_model_for_context: List[str] = field(default_factory=list)
    last_current_answer: Optional[str] = None
    ran_out_of_steps_signal: bool = False
    final_answer_text: Optional[str] = None
    is_final_answer_marked_done: bool = False

@dataclass
class AoTRunnerConfig(CoTConfig): # Inherits from CoTConfig
    main_model_names: List[str] = field(default_factory=lambda: list(DEFAULT_MAIN_MODEL_NAMES))
    temperature: float = DEFAULT_MAIN_TEMPERATURE
    max_steps: int = DEFAULT_MAX_STEPS
    max_reasoning_tokens: Optional[int] = None
    max_time_seconds: int = DEFAULT_MAX_TIME_SECONDS # This is for the AoT process itself
    no_progress_limit: int = DEFAULT_NO_PROGRESS_LIMIT
    pass_remaining_steps_pct: Optional[float] = None

@dataclass
class AoTResult: # Remains largely unchanged, will be part of CoTResult.process_specific_data
    final_answer: Optional[str] = None
    # reasoning_trace is now primarily in CoTResult. This can be removed or kept for backward compatibility within AoT
    reasoning_trace: List[str] = field(default_factory=list) 
    full_history_for_context: List[str] = field(default_factory=list)
    
    # Stats specific to the AoT process execution, not the orchestrator level
    total_completion_tokens: int = 0 # Tokens for AoT process steps
    total_prompt_tokens: int = 0 # Tokens for AoT process steps
    total_llm_interaction_time_seconds: float = 0.0 # LLM time for AoT process
    total_process_wall_clock_time_seconds: float = 0.0 # Wall clock for AoT process

    reasoning_completion_tokens: int = 0 # Specific to AoT's own accounting
    succeeded: bool = False
    # Note: The summary string (aot_summary_output) that was in the old Solution will now be generated by AoTProcessor.get_summary()

# The old 'Solution' dataclass is removed from this file.
# It is replaced by 'OrchestratorSolution' in 'orchestrator_solution.py'.
